<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/Form/HTMasterPalletMonitoring.Master"  CodeBehind="HT_PAIRING_UPDATE.aspx.cs" Inherits="FGWHSEClient.Form.HT_PAIRING_UPDATE" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

<script language="javascript" type="text/javascript">
 function onScanLot(e) 
 {
  
    if (e.keyCode == 13) 
    {
//        document.getElementById('<%= "ctl00_ContentPlaceHolder1_btnLot" %>').click();
        document.getElementById("<%= btnLot.ClientID %>").click();
    }
    
 }
 
 
 function onScanRFID(e) 
 {
  
    if (e.keyCode == 13) 
    {
//        document.getElementById('<%= "ctl00_ContentPlaceHolder1_btnRFID" %>').click();
          document.getElementById("<%= btnRFID.ClientID %>").click();     
    }
    
 }
</script>

<div style =" left:40px;top:110px; font-weight:600;">
<table>
<tr>
    <td>&nbsp;&nbsp;PPD UPDATE LOT-RFID PAIRING</td>
</tr>
<tr style="font-size:small">
    <td></td>
    <td>
        <table>
            <tr style="display:none">
                <td>&nbsp;&nbsp;&nbsp;</td>
                <td>Area Code :</td>
                <td>
                    <asp:DropDownList ID="ddArea" runat="server">
                    </asp:DropDownList>
                </td>
            </tr>
            
        </table>
    </td>
</tr>
</table>
        <div style="display:none;">
            <asp:Label ID="lblLastPartcode" runat="server" Text=""></asp:Label>
            <asp:Button ID="btnLot" runat="server" Text="" onclick="btnLot_Click" />
            <asp:Button ID="btnRFID" runat="server" Text="" onclick="btnRFID_Click" />
            
        </div>
        <div class="divInputContainer">
        <table style ="text-align:left; font-size:small">
              <tr>
                <td class="style4">
                    SCAN LOT QR :
                </td>
                <td>
                    <asp:TextBox ID="txtLot" runat="server" Height="38px" Width="311px" onkeyup="onScanLot(event)"></asp:TextBox>
                </td>
              </tr>
             
              
                
          </table>
          <br />
                <div style="overflow:auto; width:450px; height:120px; font-size:small">
                    <asp:GridView ID="grdPair" runat="server" AutoGenerateColumns="false" 
                        AutoGenerateDeleteButton="True" onrowdeleting="grdPair_RowDeleting">
                         
                         <Columns>
                            <asp:TemplateField HeaderText="ITEM CODE" >
                                <ItemTemplate>
                                    <asp:Label ID="lblItemCode" Width="100px" runat="server" Text='<%# Eval("ItemCode") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            
                            <asp:TemplateField HeaderText="LOT NO" >
                                <ItemTemplate>
                                    <asp:Label ID="lblLotNo" Width="150px" runat="server" Text='<%# Eval("LotNo") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            
                            <asp:TemplateField HeaderText="REF NO" >
                                <ItemTemplate>
                                    <asp:Label ID="lblRefNo" Width="200px" runat="server" Text='<%# Eval("RefNo") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            
                            <asp:TemplateField HeaderText="QTY" >
                                <ItemTemplate>
                                    <asp:Label ID="lblQty" Width="40px" runat="server" Text='<%# Eval("Qty") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            
                            <asp:TemplateField HeaderText="REMARKS" >
                                <ItemTemplate>
                                    <asp:Label ID="lblRemarks" Width="150px" runat="server" Text='<%# Eval("Remarks") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                         </Columns>
                         <HeaderStyle  Font-Bold="True"  BackColor = "#C5D9F1" BorderStyle ="Solid" BorderColor ="Black" />
                    
                    </asp:GridView>
                </div>
                <br />
          <table>
            <tr>
                <td colspan ="2">
                <br />
                <div style=" margin-left:80px; width: 328px;">
                    <table>
                        <tr>
                            <td>RFID Count</td>
                            <td>&nbsp;
                                <asp:TextBox ID="txtRFIDTotalcount" runat="server" Width="54px" Height="26px" 
                                    BackColor="#CCCCCC" ReadOnly="True"></asp:TextBox>
                            </td>
                            <td>&nbsp;&nbsp;&nbsp;</td>
                            <td>Total Qty</td>
                            <td> &nbsp;<asp:TextBox ID="txtTotalQty" runat="server" Width="54px" Height="26px" 
                                    BackColor="#CCCCCC" ReadOnly="True"></asp:TextBox></td>
                        </tr>
                    </table>
                </div>
                <br />
                </td>
              </tr>
              
              <tr>
                <td class="style4">
                    SCAN RFID :
                </td>
                <td>
                    <asp:TextBox ID="txtScannedRFID" runat="server" Height="38px" Width="311px" onkeyup="onScanRFID(event)"></asp:TextBox>
                </td>
              </tr>
              
              <tr>
                <td class="style4">
                    MESSAGE :
                </td>
                <td>
                    <asp:TextBox ID="txtMSG" runat="server" Height="38px" Width="311px" 
                        BackColor="#CCCCCC" ReadOnly="True"></asp:TextBox>
                </td>
              </tr>
              <tr style ="text-align:center">
                <td></td>
                <td>
                    <table>
                        <tr>
                            <td><asp:Button ID="btnClear" runat="server" Text="CLEAR" onclick="btnClear_Click" /></td>
                            <td>&nbsp;&nbsp;&nbsp;</td>
                            <td><asp:Button ID="btnSave" runat="server" Text="SAVE" onclick="btnSave_Click"  /></td>
                        </tr>
                    </table>
                
                </td>
              </tr>
          </table>
         </div>
          
          
        </div>

</asp:Content>
<asp:Content ID="Content2" runat="server" contentplaceholderid="head">

    <link type="text/css" rel="Stylesheet" href="../App_Themes/Stylesheet/Main.css"/>  
    
     

    
    <style type="text/css">
        .style4
        {
            width: 146px;
        }
    </style>





</asp:Content>
