using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FGWHSEClient.Classes
{
    public class ObjectPartsSimulationByPlant
    {
        public string Plant { get; set; }
        public string MaterialNumber { get; set; }
        public string MainVendor { get; set; }
        public string FirstColumnName { get; set; }
        public string Past { get; set; }
        public string DAY1 { get; set; }
        public string DAY2 { get; set; }
        public string DAY3 { get; set; }
        public string DAY4 { get; set; }
        public string DAY5 { get; set; }
        public string DAY6 { get; set; }
        public string DAY7 { get; set; }
        public string DAY8 { get; set; }
        public string DAY9 { get; set; }
        public string DAY10 { get; set; }
        public string DAY11 { get; set; }
        public string DAY12 { get; set; }
        public string DAY13 { get; set; }
        public string DAY14 { get; set; }
        public string DAY15 { get; set; }
        public string DAY16 { get; set; }
        public string DAY17 { get; set; }
        public string DAY18 { get; set; }
        public string DAY19 { get; set; }
        public string DAY20 { get; set; }
        public string DAY21 { get; set; }
        public string DAY22 { get; set; }
        public string DAY23 { get; set; }
        public string DAY24 { get; set; }
        public string DAY25 { get; set; }
        public string DAY26 { get; set; }
        public string DAY27 { get; set; }
        public string DAY28 { get; set; }
        public string DAY29 { get; set; }
        public string DAY30 { get; set; }
        public string DAY31 { get; set; }
        public string DAY32 { get; set; }
        public string DAY33 { get; set; }
        public string DAY34 { get; set; }
        public string DAY35 { get; set; }
        public string DAY36 { get; set; }
        public string DAY37 { get; set; }
        public string DAY38 { get; set; }
        public string DAY39 { get; set; }
        public string DAY40 { get; set; }
        public string DAY41 { get; set; }
        public string DAY42 { get; set; }
        public string DAY43 { get; set; }
        public string DAY44 { get; set; }
        public string DAY45 { get; set; }
        public string DAY46 { get; set; }
        public string DAY47 { get; set; }
        public string DAY48 { get; set; }
        public string DAY49 { get; set; }
        public string DAY50 { get; set; }
        public string DAY51 { get; set; }
        public string DAY52 { get; set; }
        public string DAY53 { get; set; }
        public string DAY54 { get; set; }
        public string DAY55 { get; set; }
        public string DAY56 { get; set; }
        public string DAY57 { get; set; }
        public string DAY58 { get; set; }
        public string DAY59 { get; set; }
        public string DAY60 { get; set; }
        public string DAY61 { get; set; }
        public string DAY62 { get; set; }
        public string DAY63 { get; set; }
        public string DAY64 { get; set; }
        public string DAY65 { get; set; }
        public string DAY66 { get; set; }
        public string DAY67 { get; set; }
        public string DAY68 { get; set; }
        public string DAY69 { get; set; }
        public string DAY70 { get; set; }
        public string DAY71 { get; set; }
        public string DAY72 { get; set; }
        public string DAY73 { get; set; }
        public string DAY74 { get; set; }
        public string DAY75 { get; set; }
        public string DAY76 { get; set; }
        public string DAY77 { get; set; }
        public string DAY78 { get; set; }
        public string DAY79 { get; set; }
        public string DAY80 { get; set; }
        public string DAY81 { get; set; }
        public string DAY82 { get; set; }
        public string DAY83 { get; set; }
        public string DAY84 { get; set; }
        public string DAY85 { get; set; }
        public string DAY86 { get; set; }
        public string DAY87 { get; set; }
        public string DAY88 { get; set; }
        public string DAY89 { get; set; }
        public string DAY90 { get; set; }
        public string DAY91 { get; set; }
        public string DAY92 { get; set; }
        public string DAY93 { get; set; }
        public string DAY94 { get; set; }
        public string DAY95 { get; set; }
        public string DAY96 { get; set; }
        public string DAY97 { get; set; }
        public string DAY98 { get; set; }
        public string DAY99 { get; set; }
        public string DAY100 { get; set; }
        public string DAY101 { get; set; }
        public string DAY102 { get; set; }
        public string DAY103 { get; set; }
        public string DAY104 { get; set; }
        public string DAY105 { get; set; }
        public string DAY106 { get; set; }
        public string DAY107 { get; set; }
        public string DAY108 { get; set; }
        public string DAY109 { get; set; }
        public string DAY110 { get; set; }
        public string DAY111 { get; set; }
        public string DAY112 { get; set; }
        public string DAY113 { get; set; }
        public string DAY114 { get; set; }
        public string DAY115 { get; set; }
        public string DAY116 { get; set; }
        public string DAY117 { get; set; }
        public string DAY118 { get; set; }
        public string DAY119 { get; set; }
        public string DAY120 { get; set; }
        public string DAY121 { get; set; }
        public string DAY122 { get; set; }
        public string DAY123 { get; set; }
        public string DAY124 { get; set; }
        public string DAY125 { get; set; }
        public string DAY126 { get; set; }
        public string DAY127 { get; set; }
        public string DAY128 { get; set; }
        public string DAY129 { get; set; }
        public string DAY130 { get; set; }
        public string DAY131 { get; set; }
        public string DAY132 { get; set; }
        public string DAY133 { get; set; }
        public string DAY134 { get; set; }
        public string DAY135 { get; set; }
        public string DAY136 { get; set; }
        public string DAY137 { get; set; }
        public string DAY138 { get; set; }
        public string DAY139 { get; set; }
        public string DAY140 { get; set; }
        public string DAY141 { get; set; }
        public string DAY142 { get; set; }
        public string DAY143 { get; set; }
        public string DAY144 { get; set; }
        public string DAY145 { get; set; }
        public string DAY146 { get; set; }
        public string DAY147 { get; set; }
        public string DAY148 { get; set; }
        public string DAY149 { get; set; }
        public string DAY150 { get; set; }
        public string DAY151 { get; set; }
        public string DAY152 { get; set; }
        public string DAY153 { get; set; }
        public string DAY154 { get; set; }
        public string DAY155 { get; set; }
        public string DAY156 { get; set; }
        public string DAY157 { get; set; }
        public string DAY158 { get; set; }
        public string DAY159 { get; set; }
        public string DAY160 { get; set; }
        public string DAY161 { get; set; }
        public string DAY162 { get; set; }
        public string DAY163 { get; set; }
        public string DAY164 { get; set; }
        public string DAY165 { get; set; }
        public string DAY166 { get; set; }
        public string DAY167 { get; set; }
        public string DAY168 { get; set; }
        public string DAY169 { get; set; }
        public string DAY170 { get; set; }
        public string DAY171 { get; set; }
        public string DAY172 { get; set; }
        public string DAY173 { get; set; }
        public string DAY174 { get; set; }
        public string DAY175 { get; set; }
        public string DAY176 { get; set; }
        public string DAY177 { get; set; }
        public string DAY178 { get; set; }
        public string DAY179 { get; set; }
        public string DAY180 { get; set; }
        public string DAY181 { get; set; }
        public string DAY182 { get; set; }
        public string DAY183 { get; set; }
        public string DAY184 { get; set; }
        public string DAY185 { get; set; }
        public string DAY186 { get; set; }
        public string DAY187 { get; set; }
        public string DAY188 { get; set; }
        public string DAY189 { get; set; }
        public string DAY190 { get; set; }
        public string DAY191 { get; set; }
        public string DAY192 { get; set; }
        public string DAY193 { get; set; }
        public string DAY194 { get; set; }
        public string DAY195 { get; set; }
        public string DAY196 { get; set; }
        public string DAY197 { get; set; }
        public string DAY198 { get; set; }
        public string User { get; set; }

    }
}